/* ------Created by----- */
-- Ayala Daniel.
-- Murillo Mario.
/* -------------------- */




/* -------------------- */
--  DATABASE SCHEMA.
/* -------------------- */

DROP DATABASE IF EXISTS CINE;

CREATE DATABASE CINE;

USE CINE;

CREATE TABLE `ESTADOS` (
  `ID` int(11) NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `NOMBRE_CORTO` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `MUNICIPIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `cve_mun` int(3) unsigned zerofill DEFAULT NULL,
  `ESTADO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MunicipioEstado` (`ESTADO`),
  CONSTRAINT `FK_MunicipioEstado` FOREIGN KEY (`ESTADO`) REFERENCES `estados` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `CINES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MUNICIPIO` int(11) NOT NULL,
  `DIRECCION` varchar(255) NOT NULL,
  `VIP` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `FK_CineMunicipio` (`MUNICIPIO`),
  CONSTRAINT `FK_CineMunicipio` FOREIGN KEY (`MUNICIPIO`) REFERENCES `municipios` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `SALAS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `PANTALLA` varchar(100) DEFAULT NULL,
  `CAPACIDAD` int(11) NOT NULL,
  `TIPO` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `SALA_CINE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CINE` int(11) NOT NULL,
  `ID_SALA` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `ASIENTOS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FILA` char(1) DEFAULT NULL,
  `NOASIENTO` tinyint(1) DEFAULT NULL,
  `ID_SALA` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SalaAsiento` (`ID_SALA`),
  CONSTRAINT `FK_SalaAsiento` FOREIGN KEY (`ID_SALA`) REFERENCES `salas` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `PELICULAS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(100) NOT NULL,
  `CATEGORIA` varchar(255) NOT NULL,
  `SINOPSIS` text NOT NULL,
  `DURACION` time DEFAULT NULL,
  `LENGUAJES` enum('SPANISH','ENGLISH') DEFAULT NULL,
  `EXPERIENCIAS` varchar(255) DEFAULT NULL,
  `FECHA_REGISTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FECHA_ESTRENO` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `FUNCIONES` (
  `ID` bigint(20) AUTO_INCREMENT,
  `ID_PELICULA` bigint(20) NOT NULL,
  `ID_SALA_CINE` bigint(20) NOT NULL,
  `Caracteristicas` varchar(100) NOT NULL,
  `FECHA_HORA` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TIPO_BOLETO` (
  `ID` int(11) AUTO_INCREMENT,
  `TIPO` varchar(50) NOT NULL,
  `Precio` double(10,2) NOT NULL,
  `ID_CINE` int(11) NOT NULL,
  PRIMARY KEY(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `BOLETOS` (
  `ID` bigint(20) AUTO_INCREMENT,
  `ID_FUNCION` bigint(20) NOT NULL,
  `ID_TIPO` int(11) NOT NULL,
  `FILA` char(1) NOT NULL,
  `ASIENTO` tinyint(1) NOT NULL,
  `ESTADO` tinyint(1) NOT NULL,
  PRIMARY KEY(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `EMPLEADOS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RFC` varchar(20) DEFAULT NULL,
  `NOMBRE` varchar(50) DEFAULT NULL,
  `APELLIDOPAT` varchar(50) DEFAULT NULL,
  `APELLIDOMAT` varchar(50) DEFAULT NULL,
  `FECHA_NAC` varchar(50) DEFAULT NULL,
  `CELULAR` varchar(21) DEFAULT NULL,
  `ID_SALARIO` int(11) DEFAULT NULL,
  `ID_SUPERIOR` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `PUESTOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `DESCRIPCION` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `SALARIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CINE` int(11) DEFAULT NULL,
  `ID_PUESTO` int(11) DEFAULT NULL,
  `SALARIO` double(10,2) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SalarioPuesto` (`ID_PUESTO`),
  KEY `FK_SalarioCine` (`ID_CINE`),
  CONSTRAINT `FK_SalarioCine` FOREIGN KEY (`ID_CINE`) REFERENCES `cines` (`ID`),
  CONSTRAINT `FK_SalarioPuesto` FOREIGN KEY (`ID_PUESTO`) REFERENCES `puestos` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `CLIENTES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `APELLIDOPAT` varchar(50) NOT NULL,
  `APELLIDOMAT` varchar(50) NOT NULL,
  `FEC_NAC` date NOT NULL,
  `TELEFONO` varchar(21) NOT NULL,
  `CATEGORIA` smallint(6) NOT NULL,
  `PUNTOS` int(11) NOT NULL DEFAULT '0',
  `FECHA_REGISTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `VENTA_BOLETO` (
  `ID_VENTA` bigint(20) NOT NULL,
  `ID_BOLETO` bigint(20) NOT NULL,
  `precio` double(10,2) NOT NULL,
  PRIMARY KEY(`ID_VENTA`,`ID_BOLETO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `VENTA_BOLETO` (
  `ID_VENTA` bigint(20) NOT NULL,
  `ID_BOLETO` bigint(20) NOT NULL,
  `precio` double(10,2) NOT NULL,
  PRIMARY KEY(`ID_VENTA`,`ID_BOLETO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `VENTAS` (
  `ID` bigint(20) AUTO_INCREMENT,
  `FECHA_HORA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ID_CLIENTE` bigint(20) DEFAULT NULL,
  `ID_EMPLEADO` bigint(20) NOT NULL,
  PRIMARY KEY(`ID_VENTA`,`ID_BOLETO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PRODUCTOS` (
  `ID` bigint(20) AUTO_INCREMENT,
  `ID_MARCA` int(11),
  `NOMBRE` varchar(100) NOT NULL,
  `PROCEDENCIA` enum('DULCERIA','CAFETERIA') NOT NULL,
  `DESCRIPCION` varchar(255) NOT NULL,
  `COMBO` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `COMBOS` (
  `ID_COMBO` bigint(20),
  `ID_PRODUCTO` bigint(20),
  `CANTIDAD` tinyint(1),
  PRIMARY KEY (`ID_COMBO`,`ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `MARCAS` (
  `ID` int(11) AUTO_INCREMENT,
  `NOMBRE` varchar(250) NOT NULL,
  `COMPANIA` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `PROVEEDOR` (
  `ID` int(11) AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `APELLIDO` varchar(100) NOT NULL,
  `TELEFONO` varchar(21) NOT NULL,
  PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `MARCA_PROVEEDOR` (
  `ID` int(11) AUTO_INCREMENT,
  `ID_MARCA` int(11) NOT NULL,
  `ID_PROVEEDOR` int(11) NOT NULL,
  `ID_LOCALIDAD` int(11) NOT NULL
  PRIMARY KEY (`ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PRODUCTO_CINE` (
  `ID` bigint(20) AUTO_INCREMENT,
  `ID_CINE` int(11) NOT NULL,
  `ID_PRODUCTO` bigint(20) NOT NULL,
  `PRECIO` double(10,2) NOT NULL,
  `DISPONIBILIDAD` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `VENTA_PRODUCTOS` (
  `ID_VENTA` bigint(20) NOT NULL,
  `ID_PRODUCTO` bigint(20) NOT NULL,
  `CANTIDAD` int(11) DEFAULT NULL,
  `PRECIO` double(10,2) NOT NULL,
  `IMPORTE` double(10,2) GENERATED ALWAYS AS(CANTIDAD*PRECIO),
  PRIMARY KEY (`ID_VENTA`,`ID_PRODUCTO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




/* -------------- */
--  CONSTRAINTS
/* -------------- */


ALTER TABLE `FUNCIONES` ADD CONSTRAINT `FK_FuncionPelicula` FOREIGN KEY (`ID_PELICULA`) REFERENCES `PELICULAS` (`ID`);
ALTER TABLE `FUNCIONES` ADD CONSTRAINT `FK_FuncionSala` FOREIGN KEY (`ID_SALA_CINE`) REFERENCES `SALAS` (`ID`);

ALTER TABLE `EMPLEADOS` ADD CONSTRAINT `FK_EmpleadoSalario` FOREIGN KEY (`ID_SALARIO`) REFERENCES `SALARIOS` (`ID`);

ALTER TABLE `BOLETOS` ADD CONSTRAINT `FK_BoletoTipo` FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPO_BOLETO` (`ID`);

ALTER TABLE `VENTAS` ADD CONSTRAINT `FK_VentaCliente` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTES` (`ID`);
ALTER TABLE `VENTAS` ADD CONSTRAINT `FK_VentaEmpleado` FOREIGN KEY (`ID_EMPLEADO`) REFERENCES `EMPLEADOS` (`ID`);

ALTER TABLE `VENTA_BOLETO` ADD CONSTRAINT `FK_VentaboletoVenta` FOREIGN KEY (`ID_VENTA`) REFERENCES `VENTAS` (`ID`);
ALTER TABLE `VENTA_BOLETO` ADD CONSTRAINT `FK_VentaboletoBoleto` FOREIGN KEY (`ID_BOLETO`) REFERENCES `BOLETOS` (`ID`);

ALTER TABLE `VENTA_PRODUCTOS` ADD CONSTRAINT `FK_VentaproductoVenta` FOREIGN KEY (`ID_VENTA`) REFERENCES `VENTAS` (`ID`);
ALTER TABLE `VENTA_PRODUCTOS` ADD CONSTRAINT `FK_VentaproductoProducto` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTOS` (`ID`);

ALTER TABLE `PRODUCTOS` ADD CONSTRAINT `KF_ProdutosMarca` FOREIGN KEY (`ID_MARCA`) REFERENCES `MARCAS` (`ID`);

ALTER TABLE `MARCA_PROVEEDOR` ADD CONSTRAINT `KF_MarcaproveedorMarca` FOREIGN KEY (`ID_MARCA`) REFERENCES `MARCAS` (`ID`);
ALTER TABLE `MARCA_PROVEEDOR` ADD CONSTRAINT `FK_MarcaproveedorProvedor` FOREIGN KEY (`ID_PROVEEDOR`) REFERENCES `PROVEEDOR` (`ID`);
ALTER TABLE `MARCA_PROVEEDOR` ADD CONSTRAINT `FK_MarcaproveedorMunicipio` FOREIGN KEY (`ID_LOCALIDAD`) REFERENCES `MUNICIPIOS` (`ID`);

ALTER TABLE `PRODUCTO_CINE` ADD CONSTRAINT `FK_ProductocineCine` FOREIGN KEY (`ID_CINE`) REFERENCES `CINES` (`ID`);
ALTER TABLE `PRODUCTO_CINE` ADD CONSTRAINT `FK_ProductocineProducto` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTOS` (`ID`);

ALTER TABLE `COMBOS` ADD CONSTRAINT `FK_ComboComboproducto` FOREIGN KEY (`ID_COMBO`) REFERENCES `PRODUCTOS` (`ID`);
ALTER TABLE `COMBOS` ADD CONSTRAINT `FK_ComboProducto` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTOS` (`ID`);

ALTER TABLE `SALA_CINE` ADD CONSTRAINT `FK_SalacineCine` FOREIGN KEY (`ID_CINE`) REFERENCES `CINES` (`ID`);
ALTER TABLE `SALA_CINE` ADD CONSTRAINT `FK_SalacineSala` FOREIGN KEY (`ID_SALA`) REFERENCES `SALAS` (`ID`);




/* -------------- */
--  INDEX
/* -------------- */

CREATE INDEX `indx_NombreCliente` ON `CLIENTES` 
(`APELLIDOPAT`,`APELLIDOMAT`,`NOMBRE`);

CREATE INDEX `indx_NombreEmpleado` ON `EMPLEADOS`
(`APELLIDOPAT`,`APELLIDOMAT`,`NOMBRE`);

CREATE INDEX `indx_NombrePelicula` ON `PELICULAS`
(`TITULO`);