/* ------Created by----- */
-- Ayala Daniel.
-- Murillo Mario.
/* -------------------- */




/* -------------------- */
--  DATABASE SCHEMA.
/* -------------------- */

DROP DATABASE IF EXISTS CINE;

CREATE DATABASE CINE;

USE CINE;

CREATE TABLE `ESTADOS` (
  `ID` int(11) NOT NULL,
  `NOMBRE` varchar(50) NOT NULL,
  `NOMBRE_CORTO` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `MUNICIPIOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `cve_mun` int(3) unsigned zerofill DEFAULT NULL,
  `ESTADO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_MunicipioEstado` (`ESTADO`),
  CONSTRAINT `FK_MunicipioEstado` FOREIGN KEY (`ESTADO`) REFERENCES `estados` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `CINES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MUNICIPIO` int(11) NOT NULL,
  `DIRECCION` varchar(255) NOT NULL,
  `VIP` tinyint(1) DEFAULT ''0'',
  PRIMARY KEY (`ID`),
  KEY `FK_CineMunicipio` (`MUNICIPIO`),
  CONSTRAINT `FK_CineMunicipio` FOREIGN KEY (`MUNICIPIO`) REFERENCES `municipios` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `SALAS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `PANTALLA` varchar(100) DEFAULT NULL,
  `CAPACIDAD` int(11) NOT NULL,
  `TIPO` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;


CREATE TABLE `SALA_CINE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CINE` int(11) NOT NULL,
  `ID_SALA` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SalacineCine` (`ID_CINE`),
  KEY `FK_SalacineSala` (`ID_SALA`),
  CONSTRAINT `FK_SalacineCine` FOREIGN KEY (`ID_CINE`) REFERENCES `cines` (`ID`),
  CONSTRAINT `FK_SalacineSala` FOREIGN KEY (`ID_SALA`) REFERENCES `salas` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;


CREATE TABLE `ASIENTOS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FILA` char(1) DEFAULT NULL,
  `NOASIENTO` tinyint(1) DEFAULT NULL,
  `ID_SALA` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SalaAsiento` (`ID_SALA`),
  CONSTRAINT `FK_SalaAsiento` FOREIGN KEY (`ID_SALA`) REFERENCES `salas` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;


CREATE TABLE `PELICULAS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(100) NOT NULL,
  `CATEGORIA` varchar(255) NOT NULL,
  `SINOPSIS` text NOT NULL,
  `DURACION` time DEFAULT NULL,
  `LENGUAJES` enum('SPANISH','ENGLISH') DEFAULT NULL,
  `EXPERIENCIAS` varchar(255) DEFAULT NULL,
  `FECHA_REGISTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FECHA_ESTRENO` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

