INSERT INTO PELICULAS(TITULO,CATEGORIA, SINOPSIS, DURACION, LENGUAJES, EXPERIENCIAS) VALUES
	('ENTERRADOS', 'DRAMA',
	'Tras producirse un gran derrumbe en una mina de Asturias, Daniel, un técnico de oficina de origen argentino, queda fortuitamente atrapado junto a un grupo de compañeros en el hueco de una galería a 600 metros de profundidad.',
	'102', 'SPANISH','NORMAL, 3-D, 4-D'),

	('BLAZE', 'BIOGRAFICA', 'La película teje tres diferentes períodos en el tiempo, trenzando versiones reimaginadas del pasado, presente y futuro de Blaze Foley, la desconocida leyenda de la música del movimiento Texas Outlaw Music. Los diferentes hilos exploran su romance con Sybil Rosen, su última noche en la tierra y el impacto de sus canciones y su muerte en sus fans, amigos y enemigos.',
		'129','ENGLISH', 'NORMAL'),

	('Ruben Brandt, coleccionista', 'ANIMACION', 'Ruben Brandt es un psicoterapeuta de éxito que aplica técnicas artísticas para curar a sus pacientes, pero los personajes de los cuadros se están apoderando de sus sueños. La excusa perfecta para que Mimi, una de sus pacientes, convenza al resto de robar los cuadros que están angustiando a su doctor.',
	'94','SPANISH','NORMAL, 3-D, 4-D'),

	('Los hermanos Sisters', 'WESTERN','Corre el año 1850. Charlie y Eli Sisters viven en un mundo salvaje, en plena fiebre del oro. Son pistoleros y ambos tienen las manos manchadas de sangre. Aunque daría todo por su hermano pequeño, el introspectivo Eli sueña con poder llevar una vida normal. Un encargo de El Comodoro, que quiere eliminar a un químico buscador de oro, les llevará de Oregón a California en un viaje iniciático que pondrá a prueba el vínculo entre los dos hermanos.',
	'121', 'ENGLISH', 'NORMAL, 3-D'),

	('Steve Bannon, el gran manipulador', 'DOCUMENTAL', 'Retrato de Steve Bannon, sin duda una de las figuras clave para entender el auge que la extrema derecha está experimentando en los últimos años en el mundo occidental.',
	'85', 'ENGLISH', 'NORMAL'),

	('Compulsión', 'THRILLER', 'La tímida Esther y el carismático Robert forman una feliz y envidiable pareja. Sin embargo, el cuento de hadas que ella vive se desvanece cuando encuentra indicios de lo que parece un affaire. Decidida a confirmar sus sospechas, sigue clandestinamente los pasos de este y es testigo de cómo se cita con otra chica.',
	'80', 'ENGLISH', 'NORMAL'),

	('Vivir deprisa, amar despacio', 'DRAMA', 'Año 1990. Arthur es un joven estudiante de veinte años que vive en Rennes. Su vida cambia el día que conoce a Jacques, un escritor que vive en París con su hijo pequeño. Durante el verano, Arthur y Jacques viven una historia de amor. Pero Jacques sabe que este amor lo tienen que vivir rápidamente.',
	'132','ENGLISH','NORMAL'),

	('Pokémon: Detective Pikachu', 'ACCION', 'La historia arranca con la misteriosa desaparición del detective Harry Goodman, que obliga a su hijo Tim, de 21 años, a averiguar lo que ha sucedido. El detective Pikachu, antiguo compañero Pokémon de Harry, va a ayudarle en su investigación. Se trata de un superdetective adorable y muy divertido que asombra a todo el mundo.',
	'104', 'ESPANISH', 'NORMAL, 3-D, 4-D'),

	('La intervención', 'ACCION', 'En un pequeño lugar del país africano Yibuti, en 1976, un grupo de rebeldes somalíes secuestran un autobús escolar con 21 niños franceses y una profesora estadounidense, y llevan el vehículo hacia la frontera con Somalia. ',
	'94', 'ENGLISH', 'NORMAL, 3-D'),

	('El bailarín', 'BIOGRAFICA', 'Rusia, 1961. Rudolf Nureyev, el bailarín de ballet más grande de todos los tiempos, viaja por primera vez fuera de la Unión Soviética como miembro de la prestigiosa Kirov Ballet Company. ',
		'127','ENGLISH', 'NORMAL'),

	('Vengadores: Endgame', 'ACCION', 'El universo se halla en ruinas. Con la ayuda de sus últimos aliados, los Vengadores se reúnen una vez más para revertir las acciones de Thanos y restaurar el orden en el universo.'
		'182','SPANISH', 'NORMAL, 3-D, 4-D'),

	('Un corazón extraordinario','COMEDIA', 'Lenny, un joven de 30 años irresponsable y malcriado, es obligado por su padre a cuidar de uno de sus pacientes adolescentes, con una grave enfermedad cardiaca. Lenny rompe todas las reglas para hacer que se cumplan cada uno de los deseos de su nuevo amigo en una aventura llena de humor, ternura y emoción.',
	'101', 'ENGLISH', 'NORMAL'),

	('Bikes', 'ANIMACION', 'Bienvenidos a Spokesville, un lugar genial para vivir, trabajar y divertirse, situado entre bosques y ríos y habitado únicamente por bicicletas. Aquí vive Speedy, una bici de montaña rápida, valiente y adorable. Sus mejores amigos son Piñón, una bicicleta de paseo; Gassy, una simpática bomba de aire que regenta el taller de la ciudad, y Montana, una audaz bicicleta, inteligente y sin miedo a decir lo que piensa.',
		'92','SPANISH', 'NORMAL, 3-D, 4-D'),

		('La espía roja (Red Joan)', 'DRAMA', 'Joan Stanley es una encantadora anciana que jamás ha levantado ningún tipo de sospecha, hasta que una mañana agentes del MI5 llaman a su puerta para llevársela detenida. Ha salido a la luz uno de mayores casos de espionaje del KGB y Joan es una de las sospechosas.',
		'103', 'ENGLISH', 'NORMAL'),

		('La Llorona', 'TERROR', 'La Llorona es una aparición aterradora. Está atrapada entre el Cielo y el Infierno en un destino terrible que ha sellado ella misma. Desde hace generaciones, la mera mención de su nombre causa terror en todo el mundo. En vida, ahogó a sus propios hijos en un ataque de celos y se tiró al río después de ellos, mientras se retorcía de dolor. Ahora sus lágrimas son eternas.',
		'93', 'ENGLISH', 'NORMAL, 3-D, 4-D'),

		('El hijo del acordeonista', 'DRAMA', 'David Imaz tuvo que huir del País Vasco a mediados de los setenta, repudiado por los suyos, acusado de traición. A pesar de encontrar la felicidad en California, su pasado le sigue pesando y el sentimiento de culpa no le permite afrontar con serenidad sus últimos días de vida.',
			'95', 'SPANISH','NORMAL'),

			('El parque mágico', 'ANIMACION', 'Un asombroso parque de atracciones despierta la imaginación de una niña arrolladoramente creativa. Un día mágico, mientras June corretea por el bosque de vuelta a casa, descubre un viejo vagón de montaña rusa abandonado y se monta en él.',
				'85', 'SPANISH', 'NORMAL, 3-D'),

			('Mia y el león blanco', 'AVENTURA', 'Mia tiene 11 años cuando comienza una relación extraordinaria con Charlie, un cachorro de león blanco nacido en la granja de leones de sus padres en Sudáfrica. Durante tres años, crecen juntos y viven una amistad incondicional.',
				'98','SPANISH', 'NORMAL, 3-D'),

			('La canción de mi padre', 'DRAMA', 'Bart Millard es el líder de una banda que logra el mayor éxito del góspel con un tema que consigue más de dos millones de descargas y del que se hacen versiones en varios idiomas.',
			'110', 'ENGLISH', 'NORMAL'),

			('7 razones para huir','CINE NEGRO', 'Un matrimonio que intenta abortar a su hijo adulto. Una pareja a la que se le presenta el tercer mundo en casa. Una escalera de vecinos que no recuerdan que va después del seis. Un agente inmobiliario que intenta vender un piso con posibilidades, pero con el antiguo inquilino colgando de la lámpara.',
				'80','ENGLISH', 'NORMAL');


-- INSET PRODUCTOS ---
INSERT INTO PRODUCTO_CINE(ID_CINE, ID_PRODUCTO, PRECIO, DISPONIBILIDAD) VALUES
(1,64,'49.90',10000),
(1,65,'39.90',10000),
(1,66,'29.90',10000),
(1,67,'49.90',10000),
(1,68,'39.90',10000),
(1,69,'29.90',10000),
(1,70,'49.90',10000),
(1,71,'39.90',10000),
(1,72,'29.90',10000),
(1,73,'49.90',10000),
(1,74,'39.90',10000),
(1,75,'29.90',10000),
(1,76, '53.90', 10000),
(1,77, '50.90', 10000),
(1,78, '60.90', 10000),
(1,79, '58.90', 10000),
(1, 80, '28.90', 10000),
(1, 81, '39.90', 10000),
(1, 82, '50.90', 10000),
(1, 83, '68.90', 10000),
(1, 84, '28.90', 10000),
(1, 85, '39.90', 10000),
(1, 86, '50.90', 10000),
(1, 87, '68.90', 10000),
(1, 88, '28.90', 10000),
(1, 89, '39.90', 10000),
(1, 90, '50.90', 10000),
(1, 91, '68.90', 10000),
(1, 92, '28.90', 10000),
(1, 93, '39.90', 10000),
(1, 94, '50.90', 10000),
(1, 95, '68.90', 10000),
(1, 96, '12.90', 10000),
(1, 97, '14.90', 10000),
(1, 98, '12.90', 10000),
(1, 99, '12.90', 10000),
(1, 100, '12.90', 10000),
(1, 101, '12.90', 10000),
(1, 102, '20.00', 10000),
(1, 103, '20.00', 10000),
(1, 104, '20.00', 10000),
(1, 105, '20.00', 10000),
(1, 106, '90.00', 10000),
(1, 107, '75.00', 10000),
(1, 108, '75.00', 10000),
(1, 109, '45.00', 10000),
(1, 110, '60.00', 10000),
(1, 111, '70.00', 10000),
(1, 112, '75.00', 10000),
(1, 113, '40.00', 10000),
(1, 114, '40.00', 10000),
(1, 115, '39.90', 10000),
(1, 116, '34.90', 10000),
(1, 117, '30.00', 10000),
(1, 118, '25.00', 10000),
(1, 119, '39.90', 10000),
(1, 120, '34.90', 10000),
(1, 121, '30.00', 10000),
(1, 122, '25.00', 10000),
(1, 123, '39.90', 10000),
(1, 124, '34.90', 10000),
(1, 125, '30.00', 10000),
(1, 126, '25.00', 10000);



INSERT INTO PRODUCTO_CINE(ID_CINE, ID_PRODUCTO, PRECIO, DISPONIBILIDAD) VALUES
(3,64,'49.90',10000),
(3,65,'39.90',10000),
(3,66,'29.90',10000),
(3,67,'49.90',10000),
(3,68,'39.90',10000),
(3,69,'29.90',10000),
(3,70,'49.90',10000),
(3,71,'39.90',10000),
(3,72,'29.90',10000),
(3,73,'49.90',10000),
(3,74,'39.90',10000),
(3,75,'29.90',10000),
(3,76, '53.90', 10000),
(3,77, '50.90', 10000),
(3,78, '60.90', 10000),
(3,79, '58.90', 10000),
(3, 80, '28.90', 10000),
(3, 81, '39.90', 10000),
(3, 82, '50.90', 10000),
(3, 83, '68.90', 10000),
(3, 84, '28.90', 10000),
(3, 85, '39.90', 10000),
(3, 86, '50.90', 10000),
(3, 87, '68.90', 10000),
(3, 88, '28.90', 10000),
(3, 89, '39.90', 10000),
(3, 90, '50.90', 10000),
(3, 91, '68.90', 10000),
(3, 92, '28.90', 10000),
(3, 93, '39.90', 10000),
(3, 94, '50.90', 10000),
(3, 95, '68.90', 10000),
(3, 96, '12.90', 10000),
(3, 97, '14.90', 10000),
(3, 98, '12.90', 10000),
(3, 99, '12.90', 10000),
(3, 100, '12.90', 10000),
(3, 101, '12.90', 10000),
(3, 102, '20.00', 10000),
(3, 103, '20.00', 10000),
(3, 104, '20.00', 10000),
(3, 105, '20.00', 10000),
(3, 106, '90.00', 10000),
(3, 107, '75.00', 10000),
(3, 108, '75.00', 10000),
(3, 109, '45.00', 10000),
(3, 110, '60.00', 10000),
(3, 111, '70.00', 10000),
(3, 112, '75.00', 10000),
(3, 113, '40.00', 10000),
(3, 114, '40.00', 10000),
(3, 115, '39.90', 10000),
(3, 116, '34.90', 10000),
(3, 117, '30.00', 10000),
(3, 118, '25.00', 10000),
(3, 119, '39.90', 10000),
(3, 120, '34.90', 10000),
(3, 121, '30.00', 10000),
(3, 122, '25.00', 10000),
(3, 123, '39.90', 10000),
(3, 124, '34.90', 10000),
(3, 125, '30.00', 10000),
(3, 126, '25.00', 10000);





-- INSET MARCAS ---
INSERT INTO MARCAS(NOMBRE, COMPANIA) VALUES
	('COCA-COLA', 'COCA-COLA-COMPANY'),
	('PEPSI','PEPSICO'),
	('PALOMITAS','VERDE VALLE'),
	('RICOLINO', 'NESTLE'),
	('MARINELA', 'DANONE'),
	('BIMBO', 'BIMBO COMPANY'),
	('HARINAS','EL GALLO'),
	('CAFE MEXICO', 'CAFFENIO');
--- ---- ---- --- --

------ INSERT PRODUCTOS ----
INSERT INTO PRODUCTOS(NOMBRE, ID_MARCA, PROCEDENCIA, DESCRIPCION, COMBO) VALUES

	('COCACOLA CLASICA', 1, 'DULCERIA' , 'VASO GRANDE', 0),
	('COCACOLA CLASICA', 1, 'DULCERIA' , 'VASO MEDIANO',0),
	('COCACOLA CLASICA', 1, 'DULCERIA' , 'VASO CHICO', 0),
	('SPRITE', 1, 'DULCERIA' , 'VASO GRANDE', 0),
	('SPRITE', 1, 'DULCERIA' , 'VASO MEDIANO', 0),
	('SPRITE', 1, 'DULCERIA' , 'VASO CHICO', 0),
	('FUZE TEA', 1, 'DULCERIA' , 'VASO GRANDE',0),
  	('FUZE TEA', 1, 'DULCERIA' , 'VASO MEDIANO', 0),
	('FUZE TEA', 1, 'DULCERIA' , 'VASO CHICO',0),
	('FANTA NARANJA', 1, 'DULCERIA' , 'VASO GRANDE',0),
	('FANTA NARANJA', 1, 'DULCERIA' , 'VASO MEDIANO',0),
	('FANTA NARANJA', 1, 'DULCERIA' , 'VASO CHICO',0),
	('NACHOS', 2,'DULCERIA', 'GRANDES',0),
	('NACHOS', 2,'DULCERIA', 'MEDIANOS', 0),
	('NACHOS', 2,'DULCERIA', ' FLAMING HOT GRANDES', 0),
	('NACHOS', 2,'DULCERIA', 'FLAMING HOT MEDIANOS', 0),
	('PALOMITAS CLASICAS', 3, 'DULCERIA', 'CHICAS',0),
	('PALOMITAS CLASICAS', 3, 'DULCERIA', 'MEDIANAS',0),
	('PALOMITAS CLASICAS', 3, 'DULCERIA', 'GRANDES',0),
	('PALOMITAS CLASICAS', 3, 'DULCERIA', 'JUMBO',0),
	('PALOMITAS CHEDAR', 3, 'DULCERIA', 'CHICAS', 0),
	('PALOMITAS CHEDAR', 3, 'DULCERIA', 'MEDIANAS', 0),
	('PALOMITAS CHEDAR', 3, 'DULCERIA', 'GRANDES', 0),
	('PALOMITAS CHEDAR', 3, 'DULCERIA', 'JUMBO', 0),
	('PALOMITAS FLAMING HOT', 3, 'DULCERIA', 'CHICAS',0),
	('PALOMITAS FLAMING HOT', 3, 'DULCERIA', 'MEDIANAS',0),
	('PALOMITAS FLAMING HOT', 3, 'DULCERIA', 'GRANDES',0),
	('PALOMITAS FLAMING HOT', 3, 'DULCERIA', 'JUMBO', 0),
	('PALOMITAS CARAMELO', 3, 'DULCERIA', 'CHICAS', 0),
	('PALOMITAS CARAMELO', 3, 'DULCERIA', 'MEDIANAS', 0),
	('PALOMITAS CARAMELO', 3, 'DULCERIA', 'GRANDES', 0),
	('PALOMITAS CARAMELO', 3, 'DULCERIA', 'JUMBO',0),
	('BUBULUBU', 4, 'DULCERIA', '30GR',0),
	('RANKY', 4, 'DULCERIA', '30GR',0),
	('CHOCORETAS', 4, 'DULCERIA', '30GR',0),
	('MORITAS', 4, 'DULCERIA', '30GR',0),
	('PANDITAS', 4, 'DULCERIA', '30GR',0),
	('LUNETAS', 4, 'DULCERIA', '30GR',0),
	('GANSITO',5, 'DULCERIA', '30GR', 0),
	('PINGUINOS',5, 'DULCERIA', '30GR',0),
	('PRINCIPE',5, 'DULCERIA', '30GR',0),
	('SUAVICREMAS', 5, 'DULCERIA','30GR',0),
	('BAGUETTE', 6, 'CAFETERIA', 'CON PAPAS',0),
	('BAGUETTE', 6, 'CAFETERIA', 'S/N',0),
	('CLUB SANDWISH', 6, 'CAFETERIA','S/N',0),
	('HOT-DOG', 6, 'CAFETERIA', 'S/N',0),
	('CREPA CLASICA', 7, 'CAFETERIA', 'JAMON DE PAVO Y QUESO',0),
	('CREPA ITALIANA', 7, 'CAFETERIA', 'SALAMI, QUESO Y JITOMATE',0),
	('CREPA JAMON', 7, 'CAFETERIA', 'HUEVO, QUESO CREMA Y TOCINO',0),
	('CREPA DULCE', 7, 'CAFETERIA', 'CON CAJETA Y PLATANO',0),
	('CREPA DULCE', 7, 'CAFETERIA', 'CON CAJETA Y FRESAS',0),
	('CAFE AMERICANO', 8, 'CAFETERIA', 'JUMBO',0),
	('CAFE AMERICANO', 8, 'CAFETERIA', 'GRANDE',0),
	('CAFE AMERICANO', 8, 'CAFETERIA', 'MEDIANO',0),
	('CAFE AMERICANO', 8, 'CAFETERIA', 'CHICO',0),
	('CAFE CAPUCHINO', 8, 'CAFETERIA', 'JUMBO',0),
	('CAFE CAPUCHINO', 8, 'CAFETERIA', 'GRANDE',0),
	('CAFE CAPUCHINO', 8, 'CAFETERIA', 'MEDIANO',0),
	('CAFE CAPUCHINO', 8, 'CAFETERIA', 'CHICO',0),
	('CAFE HELADO', 8, 'CAFETERIA', 'JUMBO',0),
	('CAFE HELADO', 8, 'CAFETERIA', 'GRANDE',0),
	('CAFE HELADO', 8, 'CAFETERIA', 'MEDIANO',0),
	('CAFE HELADO', 8, 'CAFETERIA', 'CHICO',0);
-----------------------------


-- PROVEEDOR -- --
INSERT INTO PROVEEDOR(NOMBRE, APELLIDO, TELEFONO) VALUES
	('MANUEL EL INDIO','ORTEGA', '30182392'),
	('MANUEL', 'MELENDREZ', '3018294'),
	('IVAN PATO', 'IBARRA', '6623819265'),
	('OSCAR', 'LIN', '2938475834'),
	('MARIO', 'MURILLO', '3019284'),
	('CARLOS', 'BUSTAMANTE', '29182948'),
	('MARIANA', 'ZAMUDIO', '3018294'),
	('ALAN','ACOSTA', '30182947'),
	('MARIO', 'LOPEZ', '39028132'),
	('AARON', 'MINIÑO', '39283920');
---------


------ combos ---
INSERT INTO COMBOS(NOMBRE, PRECIO) VALUES
	('COMBO HOT-DOG', '121.00'),
	('COMBO CREPA', '139.90'),
	('COMBO BAGUETTE','153.00'),
	('COMBO PAREJA','181.00'),
	('COMBO AMIGOS','312.00'),
	('COMBO NACHOS','191.00');
--------------------

------- desc combos------
INSERT INTO COMBO_DESCRIPCION(ID_PRODUCTO, ID_COMBO) VALUES
-- combo hot dog
  (19, 1),
	(46,1),
	(46,1),
	(1,1),
	(1,1),
-- -- --
-- combo crepa
  (47,2),
	(19,2),
	(1,2),
	(1,2),
-- -- -- --
 -- combo baggette
  (43,3),
	(19,3),
	(1,3),
	(1,3),
-- -- --- --
 -- combo pareja
  (1,4),
	(1,4),
	(20,4),
-- -- -- -- --
-- combo amigos
	(1,5),
	(1,5),
	(1,5),
	(1,5),
	(20,5),
	(20,5),
-- -- -- -- --
 -- combo nachos
	(13,6),
	(20,6),
	(1,6),
	;
------



INSERT INTO MARCA_PROVEEDOR(ID_MARCA, ID_PROVEEDOR, ID_LOCALIDAD) VALUES
  (1,1, 1925),
  (2,2, 1925),
  (3,3, 1925),
  (4,4, 1925),
  (5,5, 1925),
  (6,6, 1925),
  (7,7, 1925),
  (8,8, 1925);
