ALTER TABLE CLIENTES
PARTITION BY RANGE COLUMNS(NOMBRE) (
    PARTITION pA VALUES LESS THAN ('A'), 
    PARTITION pB VALUES LESS THAN ('B'), 
    PARTITION pC VALUES LESS THAN ('C'),
    PARTITION pD VALUES LESS THAN ('D'), 
    PARTITION pE VALUES LESS THAN ('E'), 
    PARTITION pF VALUES LESS THAN ('F'), 
    PARTITION pG VALUES LESS THAN ('G'), 
    PARTITION pH VALUES LESS THAN ('H'), 
    PARTITION pI VALUES LESS THAN ('I'),  
    PARTITION pJ VALUES LESS THAN ('J'), 
    PARTITION pK VALUES LESS THAN ('K'), 
    PARTITION pL VALUES LESS THAN ('L'), 
    PARTITION pM VALUES LESS THAN ('M'), 
    PARTITION pN VALUES LESS THAN ('N'), 
    PARTITION pO VALUES LESS THAN ('O'), 
    PARTITION pP VALUES LESS THAN ('P'),
    PARTITION pQ VALUES LESS THAN ('Q'), 
    PARTITION pR VALUES LESS THAN ('R'), 
    PARTITION pS VALUES LESS THAN ('S'), 
    PARTITION pT VALUES LESS THAN ('T'), 
    PARTITION pU VALUES LESS THAN ('U'), 
    PARTITION pV VALUES LESS THAN ('V'), 
    PARTITION pW VALUES LESS THAN ('W'), 
    PARTITION pX VALUES LESS THAN ('X'), 
    PARTITION pY VALUES LESS THAN ('Y'), 
    PARTITION pZ VALUES LESS THAN ('Z'),  
    PARTITION p0 VALUES LESS THAN MAXVALUE
);



ALTER TABLE VENTA
PARTITION BY RANGE (YEAR('FECHA_HORA'))
SUBPARTITION BY HASH (MONTH('FECHA_HORA')) 
SUBPARTITIONS 12 (
    PARTITION p2011 VALUES LESS THAN (2012),
    PARTITION p2012 VALUES LESS THAN (2013),
    PARTITION p2013 VALUES LESS THAN (2014),
    PARTITION p2014 VALUES LESS THAN (2015),
    PARTITION p2015 VALUES LESS THAN (2016),
    PARTITION p2016 VALUES LESS THAN (2017),
    PARTITION p2018 VALUES LESS THAN (2018),
    PARTITION p2019 VALUES LESS THAN (2012),
    PARTITION p2020 VALUES LESS THAN (2013),
    PARTITION p2021 VALUES LESS THAN (2014),
    PARTITION p2022 VALUES LESS THAN (2015),
    PARTITION pmax VALUES LESS THAN MAXVALUE
);