/* ------Created by----- */
-- Ayala Daniel.
-- Murillo Mario.
/* -------------------- */




/* -------------------- */
--  VIEWS.
/* -------------------- */


-- VIEW para ver las caracteristicas de
-- los productos cambiando los ID por
-- el nombre de cada campo.
CREATE VIEW `vw_productos` AS
SELECT PC.ID AS ID,C.ID AS ID_CINE,P.ID AS ID_PRODUCTO, P.NOMBRE AS NOMBRE,
M.NOMBRE AS MARCA,PC.PRECIO AS PRECIO,
PC.DISPONIBILIDAD AS DISPONIBLE 
FROM PRODUCTO_CINE AS PC 
INNER JOIN PRODUCTOS AS P ON PC.ID_PRODUCTO=P.ID
INNER JOIN MARCAS AS M ON P.ID_MARCA=M.ID
INNER JOIN CINES AS C ON PC.ID_CINE=C.ID;




-- VIEW para descripción completa de las
-- funciones programadas en los cines.
CREATE VIEW `vw_funciones` AS
SELECT F.ID AS ID, 
P.TITULO AS TITULO,
P.CATEGORIA AS CATEGORIA,
P.SINOPSIS AS SINOPSIS,
F.CARACTERISTICAS AS CARACT,
F.FECHA_HORA AS FECHA_HORA,
M.NOMBRE AS MUNICIPIO,
E.NOMBRE AS ESTADO,
C.DIRECCION AS DIRECCION,
S.NOMBRE AS SALA,
IF(C.VIP=0,'NORMAL','VIP') AS TIPO_CINE
FROM FUNCIONES AS F
INNER JOIN PELICULAS AS P ON F.ID_PELICULA=P.ID
INNER JOIN SALAS_CINE AS SC ON F.ID_SALA_CINE=SC.ID
INNER JOIN SALAS AS S ON SC.ID_CINE=S.ID
INNER JOIN CINES AS C ON SC.ID_CINE=C.ID
INNER JOIN MUNICIPIOS AS M ON C.MUNICIPIO=M.ID
INNER JOIN ESTADOS AS E ON M.ESTADO=E.ID;

