SELECT COLUMN_NAME, COLUMN_KEY 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = ‘IGE’ AND TABLE_NAME = ‘IGE_1999’ and COLUMN_KEY IN(‘PRI’, ‘UNI’);
ALTER TABLE IGE_1999 
PARTITION BY LIST(ESTADO)(
PARTITION PartEdo1 VALUES IN (1),
PARTITION PartEdo2 VALUES IN (2),
PARTITION PartEdo3 VALUES IN (3),
PARTITION PartEdo4 VALUES IN (4),
PARTITION PartEdo5 VALUES IN (5),
PARTITION PartEdo6 VALUES IN (6),
PARTITION PartEdo7 VALUES IN (7),
PARTITION PartEdo8 VALUES IN (8),
PARTITION PartEdo9 VALUES IN (9),
PARTITION PartEdo10 VALUES IN (10),
PARTITION PartEdo11 VALUES IN (11),
PARTITION PartEdo12 VALUES IN (12),
PARTITION PartEdo13 VALUES IN (13),
PARTITION PartEdo14 VALUES IN (14),
PARTITION PartEdo15 VALUES IN (15),
PARTITION PartEdo16 VALUES IN (16),
PARTITION PartEdo17 VALUES IN (17),
PARTITION PartEdo18 VALUES IN (18),
PARTITION PartEdo19 VALUES IN (19),
PARTITION PartEdo20 VALUES IN (20),
PARTITION PartEdo21 VALUES IN (21),
PARTITION PartEdo22 VALUES IN (22),
PARTITION PartEdo25 VALUES IN (25),
PARTITION PartEdo26 VALUES IN (26),
PARTITION PartEdo27 VALUES IN (27),
PARTITION PartEdo30 VALUES IN (30),
PARTITION PartEdo31 VALUES IN (31)
);


ALTER TABLE IGE_1999 
PARTITION BY LIST(ESTADO)
SUBPARTITION BY HASH(LOCALIDAD)
SUBPARTITIONS 5(
PARTITION PartEdo1 VALUES IN (1),
PARTITION PartEdo2 VALUES IN (2),
PARTITION PartEdo3 VALUES IN (3),
PARTITION PartEdo4 VALUES IN (4),
PARTITION PartEdo5 VALUES IN (5),
PARTITION PartEdo6 VALUES IN (6),
PARTITION PartEdo7 VALUES IN (7),
PARTITION PartEdo8 VALUES IN (8),
PARTITION PartEdo9 VALUES IN (9),
PARTITION PartEdo10 VALUES IN (10),
PARTITION PartEdo11 VALUES IN (11),
PARTITION PartEdo12 VALUES IN (12),
PARTITION PartEdo13 VALUES IN (13),
PARTITION PartEdo14 VALUES IN (14),
PARTITION PartEdo15 VALUES IN (15),
PARTITION PartEdo16 VALUES IN (16),
PARTITION PartEdo17 VALUES IN (17),
PARTITION PartEdo18 VALUES IN (18),
PARTITION PartEdo19 VALUES IN (19),
PARTITION PartEdo20 VALUES IN (20),
PARTITION PartEdo21 VALUES IN (21),
PARTITION PartEdo22 VALUES IN (22),
PARTITION PartEdo25 VALUES IN (25),
PARTITION PartEdo26 VALUES IN (26),
PARTITION PartEdo27 VALUES IN (27),
PARTITION PartEdo30 VALUES IN (30),
PARTITION PartEdo31 VALUES IN (31)
);
