/*
El horoscopo chino se conforma de 12 animales, el 2019 es el año del cerdo
El siguiente sera el añio de la rata, y asi sucesivamente los doce animales, 
Y se vuelve a repetir en el 2031 (será nuevamente el año del cerdo.)
Cada año cuenta con un elemento o ascendente. Si el año termina en 0 o 1
es metal, en 2 o 3 es agua, en 4 o 5 es madera, 6 o 7 es fuego y 8 o 9 es tierra.
De modo que una persona que nace en el 2019 será un cerdo de tierra. 
*/

DELIMITER //
DROP FUNCTION IF EXISTS fc_horoscoposchinos;
CREATE FUNCTION fc_horoscoposchinos(fecha VARCHAR(10))RETURNS VARCHAR(50)
BEGIN
-- DECLARACIÓN DE VARIABLES 
DECLARE VAR_YEAR INT(11);
DECLARE VAR_ULT_DIGITO TINYINT(4);
DECLARE VAR_OP INT(11);
DECLARE VAR_HOROSCOPO VARCHAR(50);


-- EXTRAEMOS SOLO EL AÑO DE LA FECHA,
-- YA QUE SOLO TRABAJAREMOS CON ESTE.
SET VAR_YEAR= CAST(SUBSTR(fecha,7,4) AS UNSIGNED);
SET VAR_ULT_DIGITO= CAST(SUBSTR(fecha,10,1) AS UNSIGNED);

-- CALCULAR CUANTOS AÑOS HAN PASADO DESDE EL 2019.
IF VAR_YEAR > 2019 THEN
SET VAR_OP=(VAR_YEAR-2019)+1;
ELSE
SET VAR_OP=(2019-VAR_YEAR)+1;
END IF;

-- ACOTAR EL NÚMERO A UN NÚMERO DEL 1 AL 12.
WHILE VAR_OP>12 DO 
	SET VAR_OP=VAR_OP-12;
END WHILE;

-- INVERSA
IF VAR_YEAR < 2019 THEN
	IF VAR_OP>1 THEN
		SET VAR_OP=14-VAR_OP;
	END IF;
END IF;


IF VAR_OP=1 THEN
	SET VAR_HOROSCOPO='Cerdo';
ELSEIF VAR_OP=2 THEN
	SET VAR_HOROSCOPO='Rata';
ELSEIF VAR_OP=3 THEN
	SET VAR_HOROSCOPO='Buey';
ELSEIF VAR_OP=4 THEN
	SET VAR_HOROSCOPO='Tigre';
ELSEIF VAR_OP=5 THEN
	SET VAR_HOROSCOPO='Conejo';
ELSEIF VAR_OP=6 THEN
	SET VAR_HOROSCOPO='Dragon';
ELSEIF VAR_OP=7 THEN
	SET VAR_HOROSCOPO='Serpiente';
ELSEIF VAR_OP=8 THEN
	SET VAR_HOROSCOPO='Caballo';
ELSEIF VAR_OP=9 THEN
	SET VAR_HOROSCOPO='Cabra';
ELSEIF VAR_OP=10 THEN
	SET VAR_HOROSCOPO='Mono';
ELSEIF VAR_OP=11 THEN
	SET VAR_HOROSCOPO='Gallo';
ELSEIF VAR_OP=12 THEN
	SET VAR_HOROSCOPO='Perro';
END IF;

IF VAR_ULT_DIGITO=0 OR VAR_ULT_DIGITO=1 THEN
	SET VAR_HOROSCOPO=CONCAT(VAR_HOROSCOPO, ' de metal');
ELSEIF VAR_ULT_DIGITO=2 OR VAR_ULT_DIGITO=3 THEN
	SET VAR_HOROSCOPO=CONCAT(VAR_HOROSCOPO, ' de agua');
ELSEIF VAR_ULT_DIGITO=4 OR VAR_ULT_DIGITO=5 THEN
	SET VAR_HOROSCOPO=CONCAT(VAR_HOROSCOPO, ' de madera');
ELSEIF VAR_ULT_DIGITO=6 OR VAR_ULT_DIGITO=7 THEN
	SET VAR_HOROSCOPO=CONCAT(VAR_HOROSCOPO, ' de fuego');
ELSEIF VAR_ULT_DIGITO=8 OR VAR_ULT_DIGITO=9 THEN
	SET VAR_HOROSCOPO=CONCAT(VAR_HOROSCOPO, ' de tierra');
END IF;

return VAR_HOROSCOPO;

END
//
DELIMITER ;


DELIMITER //
DROP FUNCTION IF EXISTS fc_horoscoposchinos;
CREATE FUNCTION fc_horoscoposchinos2(CURP VARCHAR(18))RETURNS VARCHAR(50)
BEGIN
DECLARE ANIO VARCHAR(1);
DECLARE ANIO2 INT(11);
DECLARE ASCENDENTE VARCHAR(6);

 SET ANIO2=CAST(SUBSTR(CURP,5,1) AS UNSIGNED);
 SET ANIO=SUBSTR(CURP,6,1);

 IF ANIO2>39 THEN
 	SET ANIO2=ANIO2+1900;
 ELSE
 	SET ANIO2=ANIO2+200;
 END


IF VAR_YEAR > 2019 THEN
SET VAR_OP=(VAR_YEAR-2019)+1;
ELSE
SET VAR_OP=(2019-VAR_YEAR)+1;
END IF;

-- ACOTAR EL NÚMERO A UN NÚMERO DEL 1 AL 12.
WHILE VAR_OP>12 DO 
	SET VAR_OP=VAR_OP-12;
END WHILE;

-- INVERSA
IF VAR_YEAR < 2019 THEN
	IF VAR_OP>1 THEN
		SET VAR_OP=14-VAR_OP;
	END IF;
END IF;

 CASE ANIO
 	WHEN '0' THEN SET ASCENDENTE='METAL';
 	WHEN '1' THEN SET ASCENDENTE='METAL';
 	WHEN '2' THEN SET ASCENDENTE='AGUA';
 	WHEN '3' THEN SET ASCENDENTE='AGUA';
 	WHEN '4' THEN SET ASCENDENTE='MADERA';
 	WHEN '5' THEN SET ASCENDENTE='MADERA';
 	WHEN '6' THEN SET ASCENDENTE='FUEGO';
 	WHEN '7' THEN SET ASCENDENTE='FUEGO';
	WHEN '8' THEN SET ASCENDENTE='TIERRA';
	WHEN '9' THEN SET ASCENDENTE='TIERRA';
	ELSE SET ASCENDENTE='';

END CASE;

RETURN ASCENDENTE;

END
//
DELIMITER ;