
CREATE TABLE signosSodiaco(
ID INT(11) AUTO_INCREMENT,
SIGNO VARCHAR(50),
INICIO VARCHAR(6),
FIN VARCHAR(6),
PRIMARY KEY(ID)
);

INSERT INTO signosSodiaco(SIGNO,INICIO,FIN) VALUES
('ACUARIO','/01/20','/02/18'),
('PISCIS','/02/19','/03/20'),
('ARIES','/03/21','/04/19'),
('TAURO','/04/20','/05/20'),
('GEMINIS','/05/21','/06/20'),
('CANCER','/06/21','/07/22'),
('LEO','/07/23','/08/22'),
('VIRGO','/08/23','/09/22'),
('LIBRA','/09/23','/10/22'),
('ESCORPION','/10/23','/11/21'),
('SAGITARIO','/11/21','/12/21'),
('CAPRICORNIO','/12/22','/01/19');



DELIMITER //
DROP FUNCTION IF EXISTS fc_signoSodiaco;
CREATE FUNCTION fc_signoSodiaco(FECHA_NAC VARCHAR(10)) RETURNS VARCHAR(50)
BEGIN
	-- Declaración de variables.
	DECLARE VAR_YEAR VARCHAR(4);
	DECLARE VAR_FECHA DATE;
	DECLARE VAR_SIGNO VARCHAR(50) DEFAULT 'NULL';

	-- Convertir el parámetro recibido a tipo DATE.
	SET VAR_FECHA= STR_TO_DATE(FECHA_NAC,'%d/%m/%Y');
	-- Extraer el Año de la fecha recibida.
	SET VAR_YEAR = EXTRACT(YEAR FROM VAR_FECHA);

	-- Primero descartamos que el signo sea CAPRICORNIO.
	-- Esto es por que el parametro consta de las fechas de dos años diferentes.
	-- Por lo cual si queremos realizar una busqueda entre un rango de fechas de distintos años
	-- todos los signos caerian dentro del rango.
	IF (EXTRACT(MONTH FROM VAR_FECHA)=1 AND EXTRACT(DAY FROM VAR_FECHA)<20) OR (EXTRACT(MONTH FROM VAR_FECHA)=12 AND EXTRACT(DAY FROM VAR_FECHA)>22) THEN
		SET VAR_SIGNO='CAPRICORNIO';
	ELSE
		-- En el caso de que no sea CAPRICORNIO se procede a buscar en la tabla creada
		-- en la cual se muestra el signo con su respectivo mes y dia de inicio y final. 
		SET VAR_SIGNO=(SELECT SIGNO FROM signosSodiaco 
			WHERE (VAR_FECHA>=STR_TO_DATE(CONCAT(VAR_YEAR,INICIO),'%Y/%m/%d')
				AND VAR_FECHA<=STR_TO_DATE(CONCAT(VAR_YEAR,FIN),'%Y/%m/%d')));
	END IF;
	
	return VAR_SIGNO;
END //
DELIMITER ;


/*  ---------------- SOLUCION 2  -------------------*/
DELIMITER //
DROP FUNCTION IF EXISTS fc_signoSodiaco;
CREATE FUNCTION fc_signoSodiaco(FECHA_NAC VARCHAR(10)) RETURNS VARCHAR(50)
BEGIN
	-- Declaración de variables.
	DECLARE VAR_FECHA DATE;
	DECLARE VAR_SIGNO VARCHAR(50) DEFAULT 'NULL';

	-- Convertir el parámetro recibido a tipo DATE.
	SET VAR_FECHA= STR_TO_DATE(FECHA_NAC,'%d/%m/%Y');
	-- Extraer el Año de la fecha recibida.
	SET VAR_YEAR = EXTRACT(YEAR FROM VAR_FECHA);

	IF (EXTRACT(MONTH FROM VAR_FECHA)=12 AND EXTRACT(DAY FROM VAR_FECHA)>=22) OR (EXTRACT(MONTH FROM VAR_FECHA)=1 AND EXTRACT(DAY FROM VAR_FECHA)<=19) THEN
		SET VAR_SIGNO='CAPRICORNIO';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=1 AND EXTRACT(DAY FROM VAR_FECHA)>=20) OR (EXTRACT(MONTH FROM VAR_FECHA)=2 AND EXTRACT(DAY FROM VAR_FECHA)<=18) THEN
		SET VAR_SIGNO='ACUARIO';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=2 AND EXTRACT(DAY FROM VAR_FECHA)>=19) OR (EXTRACT(MONTH FROM VAR_FECHA)=3 AND EXTRACT(DAY FROM VAR_FECHA)<=20) THEN
		SET VAR_SIGNO='PISCIS';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=3 AND EXTRACT(DAY FROM VAR_FECHA)>=21) OR (EXTRACT(MONTH FROM VAR_FECHA)=4 AND EXTRACT(DAY FROM VAR_FECHA)<=19) THEN
		SET VAR_SIGNO='ARIES';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=4 AND EXTRACT(DAY FROM VAR_FECHA)>=20) OR (EXTRACT(MONTH FROM VAR_FECHA)=5 AND EXTRACT(DAY FROM VAR_FECHA)<=20) THEN
		SET VAR_SIGNO='TAURO';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=5 AND EXTRACT(DAY FROM VAR_FECHA)>=21) OR (EXTRACT(MONTH FROM VAR_FECHA)=6 AND EXTRACT(DAY FROM VAR_FECHA)<=20) THEN
		SET VAR_SIGNO='GEMINIS';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=6 AND EXTRACT(DAY FROM VAR_FECHA)>=21) OR (EXTRACT(MONTH FROM VAR_FECHA)=7 AND EXTRACT(DAY FROM VAR_FECHA)<=22) THEN
		SET VAR_SIGNO='CANCER';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=7 AND EXTRACT(DAY FROM VAR_FECHA)>=23) OR (EXTRACT(MONTH FROM VAR_FECHA)=8 AND EXTRACT(DAY FROM VAR_FECHA)<=22) THEN
		SET VAR_SIGNO='LEO';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=8 AND EXTRACT(DAY FROM VAR_FECHA)>=23) OR (EXTRACT(MONTH FROM VAR_FECHA)=9 AND EXTRACT(DAY FROM VAR_FECHA)<=22) THEN
		SET VAR_SIGNO='VIRGO';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=9 AND EXTRACT(DAY FROM VAR_FECHA)>=23) OR (EXTRACT(MONTH FROM VAR_FECHA)=10 AND EXTRACT(DAY FROM VAR_FECHA)<=22) THEN
		SET VAR_SIGNO='LIBRA';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=10 AND EXTRACT(DAY FROM VAR_FECHA)>=23) OR (EXTRACT(MONTH FROM VAR_FECHA)=11 AND EXTRACT(DAY FROM VAR_FECHA)<=20) THEN
		SET VAR_SIGNO='ESCORPION';
	ELSEIF (EXTRACT(MONTH FROM VAR_FECHA)=11 AND EXTRACT(DAY FROM VAR_FECHA)>=21) OR (EXTRACT(MONTH FROM VAR_FECHA)=12 AND EXTRACT(DAY FROM VAR_FECHA)<=21) THEN
		SET VAR_SIGNO='SAGITARIO';
	END IF;
	
	return VAR_SIGNO;
END //
DELIMITER ;

