DELIMITER //
CREATE FUNCTION fc_fechaNacimiento(P_ID_PERSONA varchar(7),P_CLAVE_CT varchar(23))RETURNS DATE
BEGIN
	DECLARE FECHA DATE;
	SET FECHA=(SELECT str_to_date(FECHA_NAC,'%d/%m/%Y') FROM cemabe_personal WHERE ID_PERSONA=P_ID_PERSONA AND CLAVE_CT=P_CLAVE_CT);
	return FECHA;
END
//
DELIMITER ;


DELIMITER //
CREATE FUNCTION fc_f_nac(FECHA_NAC VARCHAR(10))RETURNS DATE
BEGIN
	return str_to_date(FECHA_NAC,'%d/%m/%Y');
END
//
DELIMITER ;




-- Solucion del profe
SELECT CURP FROM cemabe_personal WHERE CURP<>'' LIMIT 20;


SELECT CURP,FNC_FECHA(CURP), DATEDIF(CURRENT_DATE(),FUC_FECHA(CURP))/365 FROM cemabe_personal WHERE CURP<>'' LIMIT 20;

CREATE DEFINER=root@localhost FUNCTION FNC_FECHA2(CURP VARCHAR(24)) RETURNS DATE
BEGIN
DECLARE FECHA VARCHAR(24);

SET FECHA=str_to_date(CONCAT('19',SUBSTR(CURP,5,6)),'%Y/%m/%d');
return FECHA;

SELECT CURP,FNC_FECHA2(CURP), DATEDIF(CURRENT_DATE(),FUC_FECHA2(CURP))/365 FROM cemabe_personal WHERE CURP<>'' LIMIT 20;
