CREATE DATABASE IF NOT EXISTS DB_IGE;
USE DB_IGE;

CREATE TABLE IF NOT EXISTS IGE_1999(
F_NAC VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NO_ENCONTR' ,
LUG_NAC INT(2) ZEROFILL DEFAULT 123456,
SEXO ENUM('H','M') DEFAULT 'M',
HOMONIMA INT(2) ZEROFILL DEFAULT 123456,
ESTADO INT(2) ZEROFILL DEFAULT 123456,
DISTRITO INT(2) ZEROFILL DEFAULT 123456,
MUNICIPIO INT(3) ZEROFILL DEFAULT 123456,
SECCION INT(4) ZEROFILL DEFAULT 123456,
LOCALIDAD INT(4) ZEROFILL DEFAULT 123456,
MANZANA INT(2) ZEROFILL DEFAULT 123456,
F_INSC VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NO_ENCONTR' ,
CP INT(11) DEFAULT 123456,
PATERNO VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NO_ENCONTRADO' ,
MATERNO VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NO_ENCONTRADO' ,
NOMBRE VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NO_ENCONTRADO' ,
COLONIA VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'NO_ENCONTRADO' ,
OCUPACION INT(2) ZEROFILL DEFAULT 123456
);

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\IGE_1999.txt' 
INTO TABLE IGE_1999 FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' IGNORE 1 ROWS; 

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\IGE_1999.txt'
INTO TABLE IGE_1999 FIELDS TERMINATED BY '\t' ENCLOSED BY '\t' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\IGE_1999.txt'
INTO TABLE IGE_1999;